# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Paula Martin Gonzalez
title: PhD student - University of Cambridge
email: name.surname@email.co.uk
website: www.github.com/paulamartingonzalez

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: paulittamg
github_username:  paulamartingonzalez
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: paulamartingonzalez
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Coming soon...

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: NA
        link: NA
        # link_text: boringcompany.com
        sub_title: NA
        caption: NA
        quote: >
          NA
        description: | # this will include new lines to allow paragraphs
            NA
            
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: NA
        caption: dates
        sub_title: name
        quote: >
          NA
        description: | # this will include new lines to allow paragraphs
          NA
          
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Soon

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
